* GP HMM fitting idea
- P(Y_{1..t}) appears to be posynomial of emission, transition, and
  initial hidden state probabilities; see forward algorithm.
- GP aims to minimize, and we don't want argmin_parms P(Y_{1..t} =
  observed; parms)
- Try argmin_parms sum_{y_{1..t}'} loss(y_{1..t}', observed)
  p(y_{1..t}'; parms) for non-negative loss score, omitting terms where it is
  zero.
  - But WIS and energy score, for example, while having a term that
    resembles this, also subtract away a term involving two
    independent simulations.  Will every loss be like that?
  - Even if every loss involves subtracting away another term, as long
    as loss is bounded then it seems reformulable... E[l(Y,X) - c
    El(X',X)] = EE[l(Y,X) - c l(X',X)] = EE[l(Y,X) - c l(X',X) + offset].
  - Check proper loss decomposition theorem relied upon by
    omniprediction paper; is it useful here?
- If there is a reasonable "simulation loss" function, are we able to
  form the expected simulation loss with a reasonable-looking
  posynomial / amount of computation?
- More pressing issue: sum-to-1 constraint not available.  This has
  broken earlier attempts.  Reformulations with logit don't appear
  helpful, involving differences of logsumexps.  Never found a helpful
  transformation.  Might check cloglog.  Need to fix the scale here to
  actually be on the xp scale, and actually make plots reflect
  convexity rather than quasiconvexity, and show the problematic cases
  for the original scale and the logit scale (e.g. in logit scale
  where we can't factorize away the issues and get something concave).
#+begin_src R
  cloglog <- function(x) log(-log(1-x))
  clogloginv <- function(x) 1 - exp(-exp(x))
  hm <- function(m) {heatmap(m, Rowv = NA, Colv = NA, scale = "none"); readline("press enter for next")}
  hm2 <- function(m, x, y) {
    m %>%
      reshape2::melt() %>% mutate(Var1 = x[Var1], Var2 = y[Var2]) %>%
      ggplot(aes(Var1, Var2)) %>%
      `+`(geom_point(aes(colour = value))) %>% `+`(scale_colour_viridis_c()) %>%
      `+`(geom_contour(aes(z = value))) %>%
      print()
    readline("press enter for next")
  }

  x <- 1:999/1000
  xp <- cloglog(x)
  ## obj_xform <- identity
  ## obj_xform <- log
  obj_xform <- cloglog
  sapply(xp, function(xpe) obj_xform(clogloginv(xpe) * clogloginv(xp))) %>% hm()
  sapply(xp, function(xpe) obj_xform(clogloginv(xpe) * clogloginv(xp))) %>% hm2(x, x)
  sapply(xp, function(xpe) obj_xform(0.5*clogloginv(xpe) + 0.5*clogloginv(xp))) %>% hm()
  sapply(xp, function(xpe) obj_xform(0.2*clogloginv(xpe) + 0.8*clogloginv(xp))) %>% hm()
  sapply(xp, function(xpe) obj_xform(clogloginv(xpe) * (1-clogloginv(xp)))) %>% hm()
  sapply(xp, function(xpe) obj_xform(0.5*clogloginv(xpe) + 0.5*(1-clogloginv(xp)))) %>% hm()
  sapply(xp, function(xpe) obj_xform(0.2*clogloginv(xpe) + 0.8*(1-clogloginv(xp)))) %>% hm()
  sapply(xp, function(xpe) obj_xform(0.8*clogloginv(xpe) + 0.2*(1-clogloginv(xp)))) %>% hm()
  sapply(xp, function(xpe) obj_xform(0.8*clogloginv(xpe) + 0.2*(1-clogloginv(xp)))) %>% hm2(x, x)
  sapply(xp, function(xpe) obj_xform(0.8*clogloginv(xpe) + 0.2*(1-clogloginv(xp)))) %>% hm2(xp, xp)
  # ^ looks bad

  plot(xp, log(clogloginv(xp)))
  plot(xp, cloglog(clogloginv(xp)))
  plot(xp, log(1 - clogloginv(xp)))
  plot(xp, cloglog(1 - clogloginv(xp)))
#+end_src
